{"message": "Exception on /login/ [GET]", "time": "2021-12-02T17:30:31.165828", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 93, in login\n    return render_template('login.html')\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 146, in render_template\n    ctx.app.update_template_context(context)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 756, in update_template_context\n    context.update(func())\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 379, in _user_context_processor\n    return dict(current_user=_get_user())\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 346, in _get_user\n    current_app.login_manager._load_user()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/login_manager.py\", line 302, in _load_user\n    raise Exception(\nException: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info."}
{"message": "Exception on /login/ [GET]", "time": "2021-12-02T17:30:31.877507", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 93, in login\n    return render_template('login.html')\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 146, in render_template\n    ctx.app.update_template_context(context)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 756, in update_template_context\n    context.update(func())\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 379, in _user_context_processor\n    return dict(current_user=_get_user())\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 346, in _get_user\n    current_app.login_manager._load_user()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/login_manager.py\", line 302, in _load_user\n    raise Exception(\nException: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info."}
{"message": "Exception on /login/ [GET]", "time": "2021-12-02T17:30:32.308443", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 93, in login\n    return render_template('login.html')\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 146, in render_template\n    ctx.app.update_template_context(context)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 756, in update_template_context\n    context.update(func())\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 379, in _user_context_processor\n    return dict(current_user=_get_user())\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 346, in _get_user\n    current_app.login_manager._load_user()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/login_manager.py\", line 302, in _load_user\n    raise Exception(\nException: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info."}
{"message": "Exception on /login/ [GET]", "time": "2021-12-02T17:30:32.557883", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 93, in login\n    return render_template('login.html')\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 146, in render_template\n    ctx.app.update_template_context(context)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 756, in update_template_context\n    context.update(func())\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 379, in _user_context_processor\n    return dict(current_user=_get_user())\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 346, in _get_user\n    current_app.login_manager._load_user()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/login_manager.py\", line 302, in _load_user\n    raise Exception(\nException: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info."}
{"message": "Exception on /login/ [GET]", "time": "2021-12-02T17:30:43.370039", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 93, in login\n    return render_template('login.html')\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 146, in render_template\n    ctx.app.update_template_context(context)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 756, in update_template_context\n    context.update(func())\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 379, in _user_context_processor\n    return dict(current_user=_get_user())\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 346, in _get_user\n    current_app.login_manager._load_user()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/login_manager.py\", line 302, in _load_user\n    raise Exception(\nException: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info."}
{"message": "Exception on /login/ [GET]", "time": "2021-12-02T17:30:44.021727", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 93, in login\n    return render_template('login.html')\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 146, in render_template\n    ctx.app.update_template_context(context)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 756, in update_template_context\n    context.update(func())\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 379, in _user_context_processor\n    return dict(current_user=_get_user())\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 346, in _get_user\n    current_app.login_manager._load_user()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/login_manager.py\", line 302, in _load_user\n    raise Exception(\nException: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info."}
{"message": "Exception on /getInfoAboutTwitterAccountName/ [POST]", "time": "2021-12-03T05:28:39.334173", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 175, in getInfoAboutTwitterAccountName\n    twitter.get_tweets(api, account['user']['screen_name'])\nAttributeError: module 'twitter' has no attribute 'get_tweets'"}
{"message": "Exception on /getInfoAboutTwitterAccountName/ [POST]", "time": "2021-12-03T05:29:21.540489", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 175, in getInfoAboutTwitterAccountName\n    twitter.get_last_tweets(api, account['user']['screen_name'])\n  File \"/home/john/Documents/osiris/osiris_1/app/twitter.py\", line 77, in get_last_tweets\n    storage.create_tweet(tweet, quote_screen_name=quote_screen_name, retweete_screen_name=retweete_screen_name)\n  File \"/home/john/Documents/osiris/osiris_1/app/storage.py\", line 209, in create_tweet\n    \"{tweet.text.replace('\"','')}\",\nAttributeError: 'Status' object has no attribute 'text'"}
{"message": "Exception on /getInfoAboutTwitterAccountName/ [POST]", "time": "2021-12-03T05:30:16.683989", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 175, in getInfoAboutTwitterAccountName\n    twitter.get_last_tweets(api, account['user']['screen_name'])\n  File \"/home/john/Documents/osiris/osiris_1/app/twitter.py\", line 77, in get_last_tweets\n    storage.create_tweet(tweet, quote_screen_name=quote_screen_name, retweete_screen_name=retweete_screen_name)\n  File \"/home/john/Documents/osiris/osiris_1/app/storage.py\", line 209, in create_tweet\n    \"{tweet.text.replace('\"','')}\",\nAttributeError: 'Status' object has no attribute 'text'"}
{"message": "Exception on /getInfoAboutTwitterAccountName/ [POST]", "time": "2021-12-03T05:31:12.258102", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 175, in getInfoAboutTwitterAccountName\n    twitter.get_last_tweets(api, account['user']['screen_name'])\n  File \"/home/john/Documents/osiris/osiris_1/app/twitter.py\", line 77, in get_last_tweets\n    storage.create_tweet(tweet, quote_screen_name=quote_screen_name, retweete_screen_name=retweete_screen_name)\n  File \"/home/john/Documents/osiris/osiris_1/app/storage.py\", line 233, in create_tweet\n    cursor.execute(query)\nsqlite3.OperationalError: near \"or\": syntax error"}
{"message": "Exception on / [GET]", "time": "2021-12-03T06:27:16.969877", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 272, in decorated_view\n    return func(*args, **kwargs)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 113, in getDocuments\n    return render_template('index.html')\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 148, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 1068, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 997, in get_template\n    return self._load_template(name, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 958, in _load_template\n    template = self.loader.load(self, name, self.make_globals(globals))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/loaders.py\", line 137, in load\n    code = environment.compile(source, name, filename)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 757, in compile\n    self.handle_exception(source=source_hint)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 925, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"/home/john/Documents/osiris/osiris_1/app/templates/index.html\", line 4, in template\n    {% block head} {% endblock %}\njinja2.exceptions.TemplateSyntaxError: unexpected '}'"}
{"message": "Exception on / [GET]", "time": "2021-12-03T06:28:01.567784", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 272, in decorated_view\n    return func(*args, **kwargs)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 113, in getDocuments\n    return render_template('index.html')\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 148, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 1068, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 997, in get_template\n    return self._load_template(name, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 958, in _load_template\n    template = self.loader.load(self, name, self.make_globals(globals))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/loaders.py\", line 137, in load\n    code = environment.compile(source, name, filename)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 757, in compile\n    self.handle_exception(source=source_hint)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 925, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"/home/john/Documents/osiris/osiris_1/app/templates/index.html\", line 4, in template\n    {% block head} {% endblock %}\njinja2.exceptions.TemplateSyntaxError: unexpected '}'"}
{"message": "Exception on / [GET]", "time": "2021-12-03T06:28:02.333291", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 272, in decorated_view\n    return func(*args, **kwargs)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 113, in getDocuments\n    return render_template('index.html')\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 148, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 1068, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 997, in get_template\n    return self._load_template(name, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 958, in _load_template\n    template = self.loader.load(self, name, self.make_globals(globals))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/loaders.py\", line 137, in load\n    code = environment.compile(source, name, filename)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 757, in compile\n    self.handle_exception(source=source_hint)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 925, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"/home/john/Documents/osiris/osiris_1/app/templates/index.html\", line 4, in template\n    {% block head} {% endblock %}\njinja2.exceptions.TemplateSyntaxError: unexpected '}'"}
{"message": "Exception on / [GET]", "time": "2021-12-03T06:29:41.484207", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 272, in decorated_view\n    return func(*args, **kwargs)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 113, in getDocuments\n    return render_template('index.html')\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 148, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 1068, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 997, in get_template\n    return self._load_template(name, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 958, in _load_template\n    template = self.loader.load(self, name, self.make_globals(globals))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/loaders.py\", line 137, in load\n    code = environment.compile(source, name, filename)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 757, in compile\n    self.handle_exception(source=source_hint)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 925, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"/home/john/Documents/osiris/osiris_1/app/templates/index.html\", line 4, in template\n    {% block head} {% endblock %}\njinja2.exceptions.TemplateSyntaxError: unexpected '}'"}
{"message": "Exception on / [GET]", "time": "2021-12-03T06:30:04.711820", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 272, in decorated_view\n    return func(*args, **kwargs)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 113, in getDocuments\n    return render_template('index.html')\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 148, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 1068, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 997, in get_template\n    return self._load_template(name, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 958, in _load_template\n    template = self.loader.load(self, name, self.make_globals(globals))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/loaders.py\", line 137, in load\n    code = environment.compile(source, name, filename)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 757, in compile\n    self.handle_exception(source=source_hint)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 925, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"/home/john/Documents/osiris/osiris_1/app/templates/index.html\", line 4, in template\n    {% block head} {% endblock %}\njinja2.exceptions.TemplateSyntaxError: unexpected '}'"}
{"message": "Exception on / [GET]", "time": "2021-12-03T06:30:06.508001", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 272, in decorated_view\n    return func(*args, **kwargs)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 113, in getDocuments\n    return render_template('index.html')\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 148, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 1068, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 997, in get_template\n    return self._load_template(name, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 958, in _load_template\n    template = self.loader.load(self, name, self.make_globals(globals))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/loaders.py\", line 137, in load\n    code = environment.compile(source, name, filename)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 757, in compile\n    self.handle_exception(source=source_hint)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 925, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"/home/john/Documents/osiris/osiris_1/app/templates/index.html\", line 4, in template\n    {% block head} {% endblock %}\njinja2.exceptions.TemplateSyntaxError: unexpected '}'"}
{"message": "Exception on / [GET]", "time": "2021-12-03T06:30:07.740847", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 272, in decorated_view\n    return func(*args, **kwargs)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 113, in getDocuments\n    return render_template('index.html')\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 148, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 1068, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 997, in get_template\n    return self._load_template(name, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 958, in _load_template\n    template = self.loader.load(self, name, self.make_globals(globals))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/loaders.py\", line 137, in load\n    code = environment.compile(source, name, filename)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 757, in compile\n    self.handle_exception(source=source_hint)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 925, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"/home/john/Documents/osiris/osiris_1/app/templates/index.html\", line 4, in template\n    {% block head} {% endblock %}\njinja2.exceptions.TemplateSyntaxError: unexpected '}'"}
{"message": "Exception on / [GET]", "time": "2021-12-03T06:30:07.874281", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 272, in decorated_view\n    return func(*args, **kwargs)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 113, in getDocuments\n    return render_template('index.html')\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 148, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 1068, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 997, in get_template\n    return self._load_template(name, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 958, in _load_template\n    template = self.loader.load(self, name, self.make_globals(globals))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/loaders.py\", line 137, in load\n    code = environment.compile(source, name, filename)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 757, in compile\n    self.handle_exception(source=source_hint)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 925, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"/home/john/Documents/osiris/osiris_1/app/templates/index.html\", line 4, in template\n    {% block head} {% endblock %}\njinja2.exceptions.TemplateSyntaxError: unexpected '}'"}
{"message": "Exception on / [GET]", "time": "2021-12-03T06:30:08.048783", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 272, in decorated_view\n    return func(*args, **kwargs)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 113, in getDocuments\n    return render_template('index.html')\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 148, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 1068, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 997, in get_template\n    return self._load_template(name, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 958, in _load_template\n    template = self.loader.load(self, name, self.make_globals(globals))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/loaders.py\", line 137, in load\n    code = environment.compile(source, name, filename)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 757, in compile\n    self.handle_exception(source=source_hint)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 925, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"/home/john/Documents/osiris/osiris_1/app/templates/index.html\", line 4, in template\n    {% block head} {% endblock %}\njinja2.exceptions.TemplateSyntaxError: unexpected '}'"}
{"message": "Exception on / [GET]", "time": "2021-12-03T06:30:08.217525", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 272, in decorated_view\n    return func(*args, **kwargs)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 113, in getDocuments\n    return render_template('index.html')\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 148, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 1068, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 997, in get_template\n    return self._load_template(name, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 958, in _load_template\n    template = self.loader.load(self, name, self.make_globals(globals))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/loaders.py\", line 137, in load\n    code = environment.compile(source, name, filename)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 757, in compile\n    self.handle_exception(source=source_hint)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 925, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"/home/john/Documents/osiris/osiris_1/app/templates/index.html\", line 4, in template\n    {% block head} {% endblock %}\njinja2.exceptions.TemplateSyntaxError: unexpected '}'"}
{"message": "Exception on / [GET]", "time": "2021-12-03T06:30:08.361283", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 272, in decorated_view\n    return func(*args, **kwargs)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 113, in getDocuments\n    return render_template('index.html')\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 148, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 1068, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 997, in get_template\n    return self._load_template(name, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 958, in _load_template\n    template = self.loader.load(self, name, self.make_globals(globals))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/loaders.py\", line 137, in load\n    code = environment.compile(source, name, filename)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 757, in compile\n    self.handle_exception(source=source_hint)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 925, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"/home/john/Documents/osiris/osiris_1/app/templates/index.html\", line 4, in template\n    {% block head} {% endblock %}\njinja2.exceptions.TemplateSyntaxError: unexpected '}'"}
{"message": "Exception on / [GET]", "time": "2021-12-03T06:51:00.606658", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 272, in decorated_view\n    return func(*args, **kwargs)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 113, in getDocuments\n    return render_template('index.html')\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 148, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 1068, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 997, in get_template\n    return self._load_template(name, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 958, in _load_template\n    template = self.loader.load(self, name, self.make_globals(globals))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/loaders.py\", line 137, in load\n    code = environment.compile(source, name, filename)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 757, in compile\n    self.handle_exception(source=source_hint)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 925, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"/home/john/Documents/osiris/osiris_1/app/templates/index.html\", line 2, in template\n    {% block content}\njinja2.exceptions.TemplateSyntaxError: unexpected '}'"}
{"message": "Exception on / [GET]", "time": "2021-12-03T06:51:01.494343", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 272, in decorated_view\n    return func(*args, **kwargs)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 113, in getDocuments\n    return render_template('index.html')\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 148, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 1068, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 997, in get_template\n    return self._load_template(name, globals)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 958, in _load_template\n    template = self.loader.load(self, name, self.make_globals(globals))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/loaders.py\", line 137, in load\n    code = environment.compile(source, name, filename)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 757, in compile\n    self.handle_exception(source=source_hint)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 925, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"/home/john/Documents/osiris/osiris_1/app/templates/index.html\", line 2, in template\n    {% block content}\njinja2.exceptions.TemplateSyntaxError: unexpected '}'"}
{"message": "Exception on / [GET]", "time": "2021-12-03T06:51:26.136980", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 272, in decorated_view\n    return func(*args, **kwargs)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 113, in getDocuments\n    return render_template('index.html')\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 147, in render_template\n    return _render(\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 128, in _render\n    rv = template.render(context)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 1291, in render\n    self.environment.handle_exception()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 925, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"/home/john/Documents/osiris/osiris_1/app/templates/index.html\", line 1, in top-level template code\n    {% extends \"base.html\" %}\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 925, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"/home/john/Documents/osiris/osiris_1/app/templates/base.html\", line 3, in template\n    {% block head}\njinja2.exceptions.TemplateSyntaxError: unexpected '}'"}
{"message": "Exception on / [GET]", "time": "2021-12-03T07:04:56.963197", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 272, in decorated_view\n    return func(*args, **kwargs)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 113, in getDocuments\n    return render_template('index.html')\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 147, in render_template\n    return _render(\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 128, in _render\n    rv = template.render(context)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 1291, in render\n    self.environment.handle_exception()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 925, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"/home/john/Documents/osiris/osiris_1/app/templates/index.html\", line 1, in top-level template code\n    {% extends \"base.html\" %}\n  File \"/home/john/Documents/osiris/osiris_1/app/templates/base.html\", line 539, in top-level template code\n    {% block content %}\n  File \"/home/john/Documents/osiris/osiris_1/app/templates/index.html\", line 3, in block 'content'\n    {% block head %}\n  File \"/home/john/Documents/osiris/osiris_1/app/templates/index.html\", line 4, in block 'head'\n    {{ super() }}\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/utils.py\", line 84, in from_obj\n    if hasattr(obj, \"jinja_pass_arg\"):\njinja2.exceptions.UndefinedError: there is no parent block called 'head'."}
{"message": "Exception on / [GET]", "time": "2021-12-03T07:04:57.760255", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_login/utils.py\", line 272, in decorated_view\n    return func(*args, **kwargs)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 113, in getDocuments\n    return render_template('index.html')\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 147, in render_template\n    return _render(\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/templating.py\", line 128, in _render\n    rv = template.render(context)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 1291, in render\n    self.environment.handle_exception()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/environment.py\", line 925, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"/home/john/Documents/osiris/osiris_1/app/templates/index.html\", line 1, in top-level template code\n    {% extends \"base.html\" %}\n  File \"/home/john/Documents/osiris/osiris_1/app/templates/base.html\", line 539, in top-level template code\n    {% block content %}\n  File \"/home/john/Documents/osiris/osiris_1/app/templates/index.html\", line 3, in block 'content'\n    {% block head %}\n  File \"/home/john/Documents/osiris/osiris_1/app/templates/index.html\", line 4, in block 'head'\n    {{ super() }}\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/jinja2/utils.py\", line 84, in from_obj\n    if hasattr(obj, \"jinja_pass_arg\"):\njinja2.exceptions.UndefinedError: there is no parent block called 'head'."}
{"message": "Exception on /getInfoAboutTwitterAccountName/ [POST]", "time": "2021-12-03T07:26:24.929744", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 180, in getInfoAboutTwitterAccountName\n    user_info.updare({\"count_tweets_in_db\": storage.read_tweets_count(twitterAccountName)})\nAttributeError: 'dict' object has no attribute 'updare'"}
{"message": "Exception on /getInfoAboutTwitterAccountName/ [POST]", "time": "2021-12-03T08:00:52.614193", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 169, in getInfoAboutTwitterAccountName\n    account = getInfoAboutAccount(api, twitterAccountName)\n  File \"/home/john/Documents/osiris/osiris_1/app/twitter.py\", line 521, in getInfoAboutAccount\n    user = api.get_user(screen_name=username)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/tweepy/api.py\", line 46, in wrapper\n    return method(*args, **kwargs)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/tweepy/api.py\", line 2426, in get_user\n    return self.request(\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/tweepy/api.py\", line 261, in request\n    raise NotFound(resp)\ntweepy.errors.NotFound: 404 Not Found\n50 - User not found."}
{"message": "Exception on /getTwits/ [POST]", "time": "2021-12-03T08:01:21.505254", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 284, in getTwitss\n    twits = getTwits([twitterAccountName],until=until,since=since)\nNameError: name 'getTwits' is not defined"}
{"message": "Exception on /getTwits/ [POST]", "time": "2021-12-03T08:22:42.214889", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 283, in getTwitss\n    twits = twitter.get_all_tweets(twitterAccountName, until, since)\n  File \"/home/john/Documents/osiris/osiris_1/app/twitter.py\", line 64, in get_all_tweets\n    tweets = api.user_timeline(screen_name=screen_name, count=200, tweet_mode = 'extended')\nAttributeError: 'str' object has no attribute 'user_timeline'"}
{"message": "Exception on /getTwits/ [POST]", "time": "2021-12-03T08:24:22.535375", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 283, in getTwitss\n    twits = twitter.get_all_tweets(api, twitterAccountName, until, since)\n  File \"/home/john/Documents/osiris/osiris_1/app/twitter.py\", line 74, in get_all_tweets\n    if not (tweets[-1].created_at < until) and (tweets[-1].created_at > since):\nTypeError: '<' not supported between instances of 'datetime.datetime' and 'str'"}
{"message": "Exception on /getTwits/ [POST]", "time": "2021-12-03T08:27:52.337206", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 283, in getTwitss\n    twits = twitter.get_all_tweets(api, twitterAccountName, until, since)\n  File \"/home/john/Documents/osiris/osiris_1/app/twitter.py\", line 74, in get_all_tweets\n    if not (tweets[-1].created_at < str(datetime.strptime(until, \"%Y-%m-%d %H:%M:%S%z\").date())) and (tweets[-1].created_at > str(datetime.strptime(since, \"%Y-%m-%d %H:%M:%S%z\").date())):\n  File \"/usr/lib/python3.8/_strptime.py\", line 568, in _strptime_datetime\n    tt, fraction, gmtoff_fraction = _strptime(data_string, format)\n  File \"/usr/lib/python3.8/_strptime.py\", line 349, in _strptime\n    raise ValueError(\"time data %r does not match format %r\" %\nValueError: time data '2021-12-03' does not match format '%Y-%m-%d %H:%M:%S%z'"}
{"message": "Exception on /getTwits/ [POST]", "time": "2021-12-03T08:28:55.600016", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 283, in getTwitss\n    twits = twitter.get_all_tweets(api, twitterAccountName, until, since)\n  File \"/home/john/Documents/osiris/osiris_1/app/twitter.py\", line 74, in get_all_tweets\n    if not (tweets[-1].created_at < str(datetime.strptime(until, \"%Y-%m-%d\").date())) and (tweets[-1].created_at > str(datetime.strptime(since, \"%Y-%m-%d\").date())):\nTypeError: '<' not supported between instances of 'datetime.datetime' and 'str'"}
{"message": "Exception on /getTwits/ [POST]", "time": "2021-12-03T08:30:11.080724", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 283, in getTwitss\n    twits = twitter.get_all_tweets(api, twitterAccountName, until, since)\n  File \"/home/john/Documents/osiris/osiris_1/app/twitter.py\", line 74, in get_all_tweets\n    if not (tweets[-1].created_at < datetime.strptime(until, \"%Y-%m-%d\").date()) and (tweets[-1].created_at > datetime.strptime(since, \"%Y-%m-%d\").date()):\nTypeError: can't compare datetime.datetime to datetime.date"}
{"message": "Exception on /getTwits/ [POST]", "time": "2021-12-03T08:32:16.466794", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 283, in getTwitss\n    twits = twitter.get_all_tweets(api, twitterAccountName, until, since)\n  File \"/home/john/Documents/osiris/osiris_1/app/twitter.py\", line 76, in get_all_tweets\n    if not (tweets[-1].created_at < datetime.strptime(until, \"%Y-%m-%d\").date()) and (tweets[-1].created_at > datetime.strptime(since, \"%Y-%m-%d\").date()):\nTypeError: can't compare datetime.datetime to datetime.date"}
{"message": "Exception on /getTwits/ [POST]", "time": "2021-12-03T08:33:55.916444", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 283, in getTwitss\n    twits = twitter.get_all_tweets(api, twitterAccountName, until, since)\n  File \"/home/john/Documents/osiris/osiris_1/app/twitter.py\", line 76, in get_all_tweets\n    break\nTypeError: can't compare datetime.datetime to datetime.date"}
{"message": "Exception on /getInfoAboutTwitterAccountName/ [POST]", "time": "2021-12-03T09:07:54.027739", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 229, in getInfoAboutTwitterAccountName\n    chartCash = twitter.get_user_mentions(twitterAccountName)\n  File \"/home/john/Documents/osiris/osiris_1/app/twitter.py\", line 504, in get_user_mentions\n    return({\"chartCashCategories\": [category for category in b.keys()], \"chartCashCount\": [number for number in b.values()], \"status_code\":200})\nAttributeError: 'tuple' object has no attribute 'keys'"}
{"message": "Exception on /getInfoAboutTwitterAccountName/ [POST]", "time": "2021-12-03T09:08:56.246137", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 229, in getInfoAboutTwitterAccountName\n    chartCash = twitter.get_user_mentions(twitterAccountName)\n  File \"/home/john/Documents/osiris/osiris_1/app/twitter.py\", line 503, in get_user_mentions\n    b = dict(b.most_common()[12])\nValueError: dictionary update sequence element #0 has length 10; 2 is required"}
{"message": "Exception on /getInfoAboutTwitterAccountName/ [POST]", "time": "2021-12-03T09:10:12.669898", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 229, in getInfoAboutTwitterAccountName\n    chartCash = twitter.get_user_mentions(twitterAccountName)\n  File \"/home/john/Documents/osiris/osiris_1/app/twitter.py\", line 507, in get_user_mentions\n    return({\"chartCashCategories\": [category for category in b.keys()], \"chartCashCount\": [number for number in b.values()], \"status_code\":200})\nAttributeError: 'tuple' object has no attribute 'keys'"}
{"message": "Exception on /getInfoAboutTwitterAccountName/ [POST]", "time": "2021-12-03T09:14:23.896967", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 243, in getInfoAboutTwitterAccountName\n    quotes_screen_name = twitter.get_tweet_quote_screen_name(twitterAccountName)\n  File \"/home/john/Documents/osiris/osiris_1/app/twitter.py\", line 605, in get_tweet_quote_screen_name\n    return({\"quote_screen_names\": [i for i in c.keys()], \"quote_screen_name_count\": [i for i in c.values()], \"status_code\": 200})\nAttributeError: 'tuple' object has no attribute 'keys'"}
{"message": "Exception on /getInfoAboutTwitterAccountName/ [POST]", "time": "2021-12-03T09:15:56.961460", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 243, in getInfoAboutTwitterAccountName\n    quotes_screen_name = twitter.get_tweet_quote_screen_name(twitterAccountName)\n  File \"/home/john/Documents/osiris/osiris_1/app/twitter.py\", line 605, in get_tweet_quote_screen_name\n    return({\"quote_screen_names\": [c[i][0] for i in range(12)], \"quote_screen_name_count\": [calendar[i][1] for i in range(12)], \"status_code\": 200})\n  File \"/home/john/Documents/osiris/osiris_1/app/twitter.py\", line 605, in <listcomp>\n    return({\"quote_screen_names\": [c[i][0] for i in range(12)], \"quote_screen_name_count\": [calendar[i][1] for i in range(12)], \"status_code\": 200})\nTypeError: 'module' object is not subscriptable"}
{"message": "Exception on /getInfoAboutTwitterAccountName/ [POST]", "time": "2021-12-03T09:20:48.184357", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 221, in getInfoAboutTwitterAccountName\n    chartUrl = getInfoFromDB(twitterAccountName)\n  File \"/home/john/Documents/osiris/osiris_1/app/twitter.py\", line 377, in getInfoFromDB\n    return({\"categories\": [b[i][0] for i in range(12)],\"count\": [b[i][1] for i in range(12)], \"status_code\":200})\n  File \"/home/john/Documents/osiris/osiris_1/app/twitter.py\", line 377, in <listcomp>\n    return({\"categories\": [b[i][0] for i in range(12)],\"count\": [b[i][1] for i in range(12)], \"status_code\":200})\nIndexError: list index out of range"}
{"message": "Exception on /getInfoAboutTwitterAccountName/ [POST]", "time": "2021-12-03T09:23:48.317016", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 247, in getInfoAboutTwitterAccountName\n    retweet_screen_names = twitter.get_tweet_retweet_screen_name(twitterAccountName)\n  File \"/home/john/Documents/osiris/osiris_1/app/twitter.py\", line 641, in get_tweet_retweet_screen_name\n    return({\"retweet_screen_names\": [c[i][0] for i in range(counter_size)], \"retweet_screen_name_count\": [c[i][1] for i in range(counter_size)], \"status_code\": 200})\nNameError: name 'counter_size' is not defined"}
{"message": "\"_status_code\": 422, \"error\": [\"info\":\"incorrect POST-request\"]", "time": "2021-12-03T09:26:00.216759"}
{"message": "Exception on /getInfoAboutTwitterAccountName/ [POST]", "time": "2021-12-03T09:46:02.602569", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 175, in getInfoAboutTwitterAccountName\n    twitter.get_all_tweets(api, account['user']['screen_name'])\nTypeError: get_all_tweets() missing 1 required positional argument: 'since'"}
{"message": "Exception on /getInfoAboutTwitterAccountName/ [POST]", "time": "2021-12-03T09:47:29.835625", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 175, in getInfoAboutTwitterAccountName\n    twitter.get_more_tweets(api, account['user']['screen_name'])\n  File \"/home/john/Documents/osiris/osiris_1/app/twitter.py\", line 55, in get_more_tweets\n    storage.create_tweet(tweet, quote_screen_name=quote_screen_name, retweete_screen_name=retweete_screen_name)\n  File \"/home/john/Documents/osiris/osiris_1/app/storage.py\", line 208, in create_tweet\n    \"{tweet.full_text.replace('\"','')}\",\nAttributeError: 'Status' object has no attribute 'full_text'"}
{"message": "Exception on /getTwits/ [POST]", "time": "2021-12-03T09:52:00.819828", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 283, in getTwitss\n    twits = twitter.get_more_tweets(api, twitterAccountName, since, until)\nTypeError: get_more_tweets() takes 2 positional arguments but 4 were given"}
{"message": "Exception on /getTwits/ [POST]", "time": "2021-12-03T09:52:54.062084", "exc_info": "Traceback (most recent call last):\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/home/john/Documents/osiris/osiris_1/app/venv/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/home/john/Documents/osiris/osiris_1/app/app.py\", line 284, in getTwitss\n    if twits['status_code'] != 200:\nTypeError: 'NoneType' object is not subscriptable"}
{"message": "{'error': 'TwitsToBoard not found'}", "time": "2021-12-03T12:29:51.922420"}
{"message": "{'error': 'TwitsToBoard not found'}", "time": "2021-12-03T12:30:39.134723"}
